version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws --version
  build:
    commands:
      - aws s3 cp data/resume_data.yml s3://$BUCKET_NAME/data/resume_data_staging.yml
      - aws s3 cp assets/welcome.css s3://$BUCKET_NAME/data/welcome_staging.css
      - aws s3 cp assets/application.js s3://$BUCKET_NAME/data/application.js
artifacts:
  files:
    - resume_data.yml
    - assets/welcome.css
    - assets/application.js
